services:
- docker
before_install:
- docker pull harmonyone/main
script:
- ./build_static.sh
- ./scripts/endpoints_test.sh
env:
  global:
    - FROM_ADDRESS=one1geu4t54askw8ny7kuepfg5dmuxdm9cjdxfdwz9
    - TO_ADDRESS=one1qtwpscs8kz2mqnkywsplz9cvpdngz6gnh45xrn
    - FROM_SHARD=0
    - TO_SHARD=0
    - AMOUNT=0.1
    - PASSPHRASE=
    - NODE=https://rosetta.s0.b.hmny.io
    - BLOCK=8697385
